[package]
name = "subkey"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
substrate-primitives = { version = "*", path = "../core/primitives" }
rand = "0.6"
clap = { version = "~2.32", features = ["yaml"] }
substrate-bip39 = "0.2.0"
tiny-bip39 = "0.6.0"
schnorrkel = "0.0.0"
rustc-hex = "2.0"

[features]
bench = []
